import Head from 'next/head';
import Hero from '../components/Hero';
import Info from '../components/Info';
import Main from '../components/Main';
import Work from '../components/Work';
import homeInfo from '../data/homeInfo';
import mainInfo from '../data/mainInfo';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor PayAPI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Work />
      <Main sections={mainInfo} />
      <Info sections={homeInfo} />
    </div>
  );
}
