import Head from 'next/head';
import Hero from '../components/Hero';
import Work from '../components/Work';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor PayAPI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Work />
    </div>
  );
}
