import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor PayAPI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>testing</h1>
      <h1 className='small'>testing</h1>
      <h2>testing</h2>
      <h3>testing</h3>
      <h3 className='small'>testing</h3>
      <h4>testing</h4>
      <p>testing</p>
      <button>Schedule a demo</button>
      <button className='secondary__light'>testing</button>
      <button className='secondary__dark'>testing</button>
    </div>
  );
}
